stages:
  - build
  - deploy

default:
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY

build:
  stage: build
  only:
    - main
    - staging
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || true
    - docker build
      --build-arg REGISTRY=${DOCKER_REGISTRY}
      --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - test-build

.deploy:
  stage: deploy
  script:
    - docker stack deploy --with-registry-auth --prune -c docker-compose.yml $CI_PROJECT_NAME
    - stack_wait $CI_PROJECT_NAME

deploy_dev:
  extends: .deploy
  variables:
    DOMAIN: -dev.testdomain.dev
    API_BASE_URL: https://front-api${DOMAIN}/
  only:
    - staging
  tags:
    - testdomain-deploy

deploy_main:
  extends: .deploy
  variables:
    DOMAIN: .testdomain.dev
    API_BASE_URL: https://front-api${DOMAIN}/
  only:
    - main
  tags:
    - main-deploy-testdomain
