version: '3.5'
services:
  app:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    container_name: ${CI_PROJECT_NAME}
    environment:
      - TZ=Europe/Moscow
      - API_BASE_URL
    deploy:
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: any
      labels:
        # - test
      replicas: 3
    networks:
      - default

networks:
  default:
    name: test
