const ca = '#202044';

export default {
  data: () => ({
    soundsIcons: [
      {
        id: '006_light_rain',
        icon_svg: 'ico_light_rain.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '029_heavy_rain',
        icon_svg: 'ico_heavy_rain.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '033_thunderstorm',
        icon_svg: 'ico_thunderstorm.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '002_birds',
        icon_svg: 'ico_birds.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '050_forest',
        icon_svg: 'ico_forest.svg',
        bg: '#2F3F45',
        bg_active: '#6ABD4B',
        icon_color: '#6ABD4B',
        icon_color_active: ca,
      },
      {
        id: '004_campfire',
        icon_svg: 'ico_campfire.svg',
        bg: '#2F3F45',
        bg_active: '#6ABD4B',
        icon_color: '#6ABD4B',
        icon_color_active: ca,
      },
      {
        id: '008_urban_rain',
        icon_svg: 'ico_urban_rain.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '079_seagulls',
        icon_svg: 'ico_seagulls.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '056_night',
        icon_svg: 'ico_night.svg',
        bg: '#2F3F45',
        bg_active: '#6ABD4B',
        icon_color: '#6ABD4B',
        icon_color_active: ca,
      },
      {
        id: '043_fire_crackles',
        icon_svg: 'ico_fire_crackles.svg',
        bg: '#2F3F45',
        bg_active: '#6ABD4B',
        icon_color: '#6ABD4B',
        icon_color_active: ca,
      },
      {
        id: '015_owls',
        icon_svg: 'ico_owls.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '035_cicadas',
        icon_svg: 'ico_cicadas.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '081_brushing_hair',
        icon_svg: 'ico_hair_brush.svg',
        bg: '#482852',
        bg_active: '#E9498C',
        icon_color: '#E9498C',
        icon_color_active: ca,
      },
      {
        id: '082_wind_chimes',
        icon_svg: 'ico_wind_chimes.svg',
        bg: '#482852',
        bg_active: '#E9498C',
        icon_color: '#E9498C',
        icon_color_active: ca,
      },
      {
        id: '093_fizzy_drink',
        icon_svg: 'ico_fizzy_drink.svg',
        bg: '#482852',
        bg_active: '#E9498C',
        icon_color: '#E9498C',
        icon_color_active: ca,
      },
      {
        id: '032_popcorn',
        icon_svg: 'ico_popcorn.svg',
        bg: '#482852',
        bg_active: '#E9498C',
        icon_color: '#E9498C',
        icon_color_active: ca,
      },
      {
        id: '094_city_ambience',
        icon_svg: 'ico_city_ambience.svg',
        bg: '#453D45',
        bg_active: '#DAB24A',
        icon_color: '#DAB24A',
        icon_color_active: ca,
      },
      {
        id: '062_coffee_shop',
        icon_svg: 'ico_coffee_shop.svg',
        bg: '#453D45',
        bg_active: '#DAB24A',
        icon_color: '#DAB24A',
        icon_color_active: ca,
      },
      {
        id: '058_rustling_leaves',
        icon_svg: 'ico_rustling_leaves.svg',
        bg: '#353669',
        bg_active: '#8B8DFC',
        icon_color: '#8B8DFC',
        icon_color_active: ca,
      },
      {
        id: '089_wind_surge',
        icon_svg: 'ico_wind_surge.svg',
        bg: '#353669',
        bg_active: '#8B8DFC',
        icon_color: '#8B8DFC',
        icon_color_active: ca,
      },
      {
        id: '019_white_noise',
        icon_svg: 'ico_noise_1.svg',
        bg: '#482A47',
        bg_active: '#E95454',
        icon_color: '#E95454',
        icon_color_active: ca,
      },
      {
        id: '026_train',
        icon_svg: 'ico_train.svg',
        bg: '#453D45',
        bg_active: '#DAB24A',
        icon_color: '#DAB24A',
        icon_color_active: ca,
      },
      {
        id: '053_winds',
        icon_svg: 'ico_winds.svg',
        bg: '#353669',
        bg_active: '#8B8DFC',
        icon_color: '#8B8DFC',
        icon_color_active: ca,
      },
      {
        id: '020_wind_in_trees',
        icon_svg: 'ico_wind_in_trees.svg',
        bg: '#353669',
        bg_active: '#8B8DFC',
        icon_color: '#8B8DFC',
        icon_color_active: ca,
      },
      {
        id: '003_brown_noise',
        icon_svg: 'ico_noise_2.svg',
        bg: '#482A47',
        bg_active: '#E95454',
        icon_color: '#E95454',
        icon_color_active: ca,
      },
      {
        id: '047_truck_engine',
        icon_svg: 'ico_truck_engine.svg',
        bg: '#453D45',
        bg_active: '#DAB24A',
        icon_color: '#DAB24A',
        icon_color_active: ca,
      },
      {
        id: '100_boiling',
        icon_svg: 'ico_boiling_water.svg',
        bg: '#293C53',
        bg_active: '#4CAA8E',
        icon_color: '#4CAA8E',
        icon_color_active: ca,
      },
      {
        id: '001_bath_filling',
        icon_svg: 'ico_bath_filling.svg',
        bg: '#293C53',
        bg_active: '#4CAA8E',
        icon_color: '#4CAA8E',
        icon_color_active: ca,
      },
      {
        id: '014_pink_noise',
        icon_svg: 'ico_noise_3.svg',
        bg: '#482A47',
        bg_active: '#E95454',
        icon_color: '#E95454',
        icon_color_active: ca,
      },
      {
        id: '088_green_noise',
        icon_svg: 'ico_noise_4.svg',
        bg: '#482A47',
        bg_active: '#E95454',
        icon_color: '#E95454',
        icon_color_active: ca,
      },
      {
        id: '037_river_stream',
        icon_svg: 'ico_river_stream.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '078_shower',
        icon_svg: 'ico_shower.svg',
        bg: '#293C53',
        bg_active: '#4CAA8E',
        icon_color: '#4CAA8E',
        icon_color_active: ca,
      },
      {
        id: '066_cavern',
        icon_svg: 'ico_cavern.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '069_ocean',
        icon_svg: 'ico_ocean.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '038_waterfall',
        icon_svg: 'ico_waterfall.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '064_hot_tub',
        icon_svg: 'ico_hot_tub.svg',
        bg: '#293C53',
        bg_active: '#4CAA8E',
        icon_color: '#4CAA8E',
        icon_color_active: ca,
      },
      {
        id: '010_crickets',
        icon_svg: 'ico_crickets.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '048_whales',
        icon_svg: 'ico_whales.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '030_keyboard',
        icon_svg: 'ico_keyboard.svg',
        bg: '#482852',
        bg_active: '#E9498C',
        icon_color: '#E9498C',
        icon_color_active: ca,
      },
      {
        id: '087_elvish_whispers',
        icon_svg: 'ico_whispers.svg',
        bg: '#482852',
        bg_active: '#E9498C',
        icon_color: '#E9498C',
        icon_color_active: ca,
      },
      {
        id: '067_frogs',
        icon_svg: 'ico_frog.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '085_air_conditioner',
        icon_svg: 'ico_ac.svg',
        bg: '#293C53',
        bg_active: '#4CAA8E',
        icon_color: '#4CAA8E',
        icon_color_active: ca,
      },
      {
        id: '028_heartbeat',
        icon_svg: 'ico_heartbeat.svg',
        bg: '#482852',
        bg_active: '#E9498C',
        icon_color: '#E9498C',
        icon_color_active: ca,
      },
      {
        id: '086_vinyl_crackle',
        icon_svg: 'ico_vinyl_crackle.svg',
        bg: '#482852',
        bg_active: '#E9498C',
        icon_color: '#E9498C',
        icon_color_active: ca,
      },
      {
        id: '084_wolf',
        icon_svg: 'ico_wolf.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '073_oscillating_fan',
        icon_svg: 'ico_fan.svg',
        bg: '#293C53',
        bg_active: '#4CAA8E',
        icon_color: '#4CAA8E',
        icon_color_active: ca,
      },
      {
        id: '083_hair_dryer',
        icon_svg: 'ico_hair_dryer.svg',
        bg: '#293C53',
        bg_active: '#4CAA8E',
        icon_color: '#4CAA8E',
        icon_color_active: ca,
      },
      {
        id: '023_grandfather_clock',
        icon_svg: 'ico_grandfather_clock.svg',
        bg: '#293C53',
        bg_active: '#4CAA8E',
        icon_color: '#4CAA8E',
        icon_color_active: ca,
      },
      {
        id: '036_rain_on_roof',
        icon_svg: 'ico_rain_on_roof.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '102_rain_nature',
        icon_svg: 'ico_rain_drops.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '101_rain_tent',
        icon_svg: 'ico_rain_on_tent.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '095_horses',
        icon_svg: 'ico_horse.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '096_rain_on_window',
        icon_svg: 'ico_rain_on_window.svg',
        bg: '#233B65',
        bg_active: '#2FA6E9',
        icon_color: '#2FA6E9',
        icon_color_active: ca,
      },
      {
        id: '099_cuckoo',
        icon_svg: 'ico_cuckoo.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '098_kasatka',
        icon_svg: 'ico_orca.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: '054_cat_purring',
        icon_svg: 'ico_cat_purring.svg',
        bg: '#483243',
        bg_active: '#E77A3D',
        icon_color: '#E77A3D',
        icon_color_active: ca,
      },
      {
        id: 'ambient_01',
        music_config: 'ambient_01',
        title_loc: 'music_title_ambient_01',
        bg: '#483243',
        icon_color: '#E77A3D',
      },
      {
        id: 'ambient_piano_01',
        music_config: 'ambient_piano_01',
        title_loc: 'music_title_ambient_piano_01',
        bg: '#353669',
        icon_color: '#8B8DFC',
      },
      {
        id: 'jazz_01',
        music_config: 'jazz_01',
        title_loc: 'music_title_jazz_01',
        bg: '#233B65',
        icon_color: '#2FA6E9',
      },
      {
        id: 'classical_piano_01',
        music_config: 'classical_piano_01',
        title_loc: 'music_title_classical_piano_01',
        bg: '#293C53',
        icon_color: '#4CAA8E',
      },
      {
        id: 'flute_01',
        music_config: 'flute_01',
        title_loc: 'music_title_flute_01',
        bg: '#453D45',
        icon_color: '#DAB24A',
      },
      {
        id: 'lofi_01',
        music_config: 'lofi_01',
        title_loc: 'music_title_lofi_01',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'guitar_01',
        music_config: 'guitar_01',
        title_loc: 'music_title_guitar_01',
        bg: '#483243',
        icon_color: '#E77A3D',
      },
      {
        id: 'baby_01',
        music_config: 'baby_01',
        title_loc: 'music_title_baby_01',
        bg: '#353669',
        icon_color: '#8B8DFC',
      },
      {
        id: 'meditation_01',
        music_config: 'meditation_01',
        title_loc: 'music_title_meditation_01',
        bg: '#293C53',
        icon_color: '#4CAA8E',
      },
      {
        id: 'lofi_02',
        music_config: 'lofi_02',
        title_loc: 'music_title_lofi_02',
        bg: '#233B65',
        icon_color: '#2FA6E9',
      },
      {
        id: 'ambient_02',
        music_config: 'ambient_02',
        title_loc: 'music_title_ambient_02',
        bg: '#482A47',
        icon_color: '#E95454',
      },
      {
        id: 'relaxing_piano_01',
        music_config: 'relaxing_piano_01',
        title_loc: 'music_title_relaxing_piano_01',
        bg: '#453D45',
        icon_color: '#DAB24A',
      },
      {
        id: 'baby_03',
        music_config: 'baby_03',
        title_loc: 'music_title_baby_03',
        bg: '#483243',
        icon_color: '#E77A3D',
      },
      {
        id: 'harp_01',
        music_config: 'harp_01',
        title_loc: 'music_title_harp_01',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'yoga_01',
        music_config: 'yoga_01',
        title_loc: 'music_title_yoga_01',
        bg: '#353669',
        icon_color: '#8B8DFC',
      },
      {
        id: 'baby_02',
        music_config: 'baby_02',
        title_loc: 'music_title_baby_02',
        bg: '#293C53',
        icon_color: '#4CAA8E',
      },
      {
        id: 'baby_04',
        music_config: 'baby_04',
        title_loc: 'music_title_baby_04',
        bg: '#353669',
        icon_color: '#8B8DFC',
      },
      {
        id: 'piano_lullaby_01',
        music_config: 'piano_lullaby_01',
        title_loc: 'music_title_piano_lullaby_01',
        bg: '#483243',
        icon_color: '#E77A3D',
      },
      {
        id: 'celtic_01',
        music_config: 'celtic_01',
        title_loc: 'music_title_celtic_01',
        bg: '#483243',
        icon_color: '#E77A3D',
      },
      {
        id: 'yoga_02',
        music_config: 'yoga_02',
        title_loc: 'music_title_yoga_02',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_0.5',
        title_loc: 'binaural_title_0.5',
        description_loc: 'binaural_description_0.5',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_1',
        title_loc: 'binaural_title_1',
        description_loc: 'binaural_description_1',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_1.5',
        title_loc: 'binaural_title_1.5',
        description_loc: 'binaural_description_1.5',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_2',
        title_loc: 'binaural_title_2',
        description_loc: 'binaural_description_2',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_2.5',
        title_loc: 'binaural_title_2.5',
        description_loc: 'binaural_description_2.5',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_4',
        title_loc: 'binaural_title_4',
        description_loc: 'binaural_description_4',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_5',
        title_loc: 'binaural_title_5',
        description_loc: 'binaural_description_5',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_8',
        title_loc: 'binaural_title_8',
        description_loc: 'binaural_description_8',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_10',
        title_loc: 'binaural_title_10',
        description_loc: 'binaural_description_10',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
      {
        id: 'binaural_20',
        title_loc: 'binaural_title_20',
        description_loc: 'binaural_description_20',
        bg: '#2F3F45',
        icon_color: '#6ABD4B',
      },
    ],
  }),

  methods: {
    getIconById(id) {
      return this.soundsIcons.find((_) => _.id === id);
    },
  },
};
